### ISSUE TITLE
No new tiles spawned after a merge/sum at the end

### ISSUE THREAD

**Issue by saltymouse** [nklunder/2048#1]
No new tiles are spawned after _just_ merging. If no other sliding/shifting of tiles occurs (other than merging/summing of tiles) no new tiles are spawned to the game board.

![screen shot 2017-11-04 at 11 09 58 pm](https://user-images.githubusercontent.com/7547649/32412468-0dd9d5d8-c23c-11e7-98b5-446b5228b63d.png)

**Comment by nklunder** [comment]
fixed in commit 7b19d542df0bcc5ae1daf5787847990dc4332ee6
